Create ajax error with server response text
mapbox/mapbox-gl-js pull request #10104
Opened 2020-11-15 12:08 UTC by kikonejacob

Closes #10097 

## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

2020-12-08 16:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=10104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=10104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-gl-js?pullRequest=10104) it.</sub>

2020-12-18 01:12 UTC, asheemmamoowala requested changes
@kikonejacob Thank you for the change. For consistency, I think this change should be made in `makeXMLHttpRequest` as well. 

Could you also add some unit tests in `https://github.com/mapbox/mapbox-gl-js/blob/main/test/unit/util/ajax.test.js` with mocked responses.

2020-12-18 01:12 UTC, asheemmamoowala commented on src/util/ajax.js
> +                response.text().then(text => {
Would you consider attempting to read `response.text()` only when `statusText` is empty?

2021-01-12 18:50 UTC, ryanhamley commented
Closing as stale. @kikonejacob if you want to pick this back up, feel free to re-open

2021-01-12 18:50 UTC, closed without merging