feat: send geolocation as adapter
mapbox/mapbox-gl-js pull request #10400
Opened 2021-02-19 08:57 UTC by behnammodi

- This PR can help developers to customize `geolocation` behavior.
 - We don't have any visual changes.
 - All test cases compatible with these changes.
 - I need your opinion and then add a document.
 
 So now we have:
 ```js
 const myGeolocation: Geolocation = {
    clearWatch: ...,
    getCurrentPosition: ...,
    watchPosition: ...,
};
 
 const geolocateControl = new GeolocateControl({
    geolocation: myGeolocation,
});

map.addControl(geolocateControl);
 ```
 
 I'll say welcome to your awesome feedback :)

2021-02-19 17:06 UTC, karimnaaji commented
As mentioned by @mourner in the other PR, CI will need to be addressed prior to review. The failed tests are build and unit-test:

https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/5924/workflows/e1c44d57-030a-42ea-ad10-1d430ff22043/jobs/80315

https://app.circleci.com/pipelines/github/mapbox/mapbox-gl-js/5924/workflows/e1c44d57-030a-42ea-ad10-1d430ff22043/jobs/80309

2021-03-08 19:55 UTC, mourner requested changes
This is still waiting for green CI builds (currently some tests are failing).

2021-04-22 09:59 UTC, behnammodi commented
Do we have any updates about this PR?

2021-10-19 09:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=10400) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=10400) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-gl-js?pullRequest=10400) it.</sub>

2022-03-17 17:07 UTC, mourner commented
I didn't know how to resolve the CI being stuck, so ended up rebasing this and making a new PR with your changes here: #11614

2022-03-17 17:07 UTC, closed without merging

2022-03-17 17:09 UTC, behnammodi commented
> I didn't know how to resolve the CI being stuck, so ended up rebasing this and making a new PR with your changes here: #11614

Go ahead