Remove unnecessary sorting when getting rendered tiles before symbol placement
mapbox/mapbox-gl-js pull request #10993
Opened 2021-09-06 09:41 UTC by zmiao

…placement

## Launch Checklist

Two times of sorting are performed when getting the rendered tiles, however, the first sorting result will anyway be overridden by the second sorting, thus remove it from the code.

The second sorting is done right after the first sorting:
https://github.com/mapbox/mapbox-gl-js/blob/63bd2945940e77749dad2797009b84353abefe6e/src/style/style.js#L1630-L1636

 - [ ] briefly describe the changes in this PR
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

2021-09-06 11:56 UTC, astojilj commented
@zmiao 
getRenderableIds(true) seems to be called also from getVisibleCoordinates() .. and further depending on that order in tile clipping masks.

https://github.com/mapbox/mapbox-gl-js/blob/63bd2945940e77749dad2797009b84353abefe6e/src/render/painter.js#L448

2021-09-06 12:16 UTC, zmiao commented
@astojilj nice catch! I will update my approach then

2021-09-06 13:21 UTC, mourner requested changes
👍 apart from a nit. Looks like the rotated sorting was originally added in #5601 to match native, but is apparently no longer necessary.

2021-09-06 13:21 UTC, mourner commented on src/source/source_cache.js
> -        if (symbolLayer) {
`symbolLayer` argument is no longer used so we should remove it from signature / calls.

2021-09-06 13:23 UTC, mourner commented
> getRenderableIds(true) seems to be called also from getVisibleCoordinates() .. and further depending on that order in tile clipping masks.

Yeah, but removing the sorting doesn't affect any render tests, which made me think it's no longer necessary for matching `native`, but maybe @ansis can chime in.

2021-09-06 14:30 UTC, zmiao commented
> Yeah, but removing the sorting doesn't affect any render tests, which made me think it's no longer necessary for matching native, but maybe @ansis can chime in.

@mourner @ansis , after checking the code, I agree that tile order will only matter for symbol placement, the other places that using `sourceCache.getVisibleCoordinates(true).reverse()` may just only want to include all of the tiles, including tiles that are hold for fade.  Maybe the `reverse()` call also be removed. 

I just tested with my above assumption in the latest commit, only following two tests are failed:
<img width="2119" alt="Screen Shot 2021-09-06 at 5 27 50 PM" src="https://user-images.githubusercontent.com/11026055/132232012-741270da-29fb-4498-956d-2338f1e6ecd9.png">

2021-09-10 17:50 UTC, rreusser reviewed
It's interesting to me that we no longer sort by z, instead sorting by zoom then ascending x/y tile coordinate. I almost wonder if what we really want is a hybrid of the two that integrates bearing into compareTileId.

One place where I think this is visible (maybe; not 100% certain) is for circle layers which use read-only depth and are affected by two orderings: 1) tile order, and 2) vertex order. If it weren't overridden, the removed sort would seem to affect the ordering of tiles of circles (though not circles within a single tile). The result is circle layering that, for two reasons (within a tile and across tiles), doesn't always make sense, e.g.:

<img width="653" alt="Screen Shot 2021-09-10 at 10 40 19 AM" src="https://user-images.githubusercontent.com/572717/132896137-0a0a989e-52a4-4660-a9c7-a141bf5747c4.png">

This PR is okay with me as removal of this redundant sort does seem to check out, though I don't completely follow the logic of compareTileId sorting by canonical.x and canonical.y _without bearing_.

Marking this review as a "comment" since it falls somewhere between not blocking the merging as this seems valid, but also not fully understanding the slightly larger goal of sorting tiles.

2021-09-10 18:47 UTC, zmiao commented
> It's interesting to me that we no longer sort by z, instead sorting by zoom then ascending x/y tile coordinate.

> This PR is okay with me as removal of this redundant sort does seem to check out, though I don't completely follow the logic of compareTileId sorting by canonical.x and canonical.y without bearing.

@rreusser to be honest, I have the same question when I cross-check the tile sorting algorithms between gl-js and gl-native. 
The reason why I remove the first sorting part is I don't have an answer which one is correct but apparently two consecutive sortings are not necessary, so I removed the first one and try to adapt code in gl-native.

In fact, gl-native was using a similar sorting algorithm that is very similar to the removed one, only with one difference, that is sorting tiles in descending zoom order instead of ascending order.  And that's the only sorting in gl-native, which in my view is actually the correct sorting approach. (due to the diverged sorting approaches, several render tests are failing in gl-native and currently, we have to skip them)

So in another way, if we use gl-native's approach, which means we could actually keep using the removed sorting algorithm but with following changes:
```git.patch
  return renderables.sort((a_: Tile, b_: Tile) => {
                const a = a_.tileID;
                const b = b_.tileID;
                const rotatedA = (new Point(a.canonical.x, a.canonical.y))._rotate(this.transform.angle);
                const rotatedB = (new Point(b.canonical.x, b.canonical.y))._rotate(this.transform.angle);
--                return a.overscaledZ - b.overscaledZ || rotatedB.y - rotatedA.y || rotatedB.x - rotatedA.x;
++               // Sort from child tile to parent tile, from bigger y corrdinates to smaller ones(near viewer tiles to further ones in case map is pitched), from smaller x corrdiantes to bigger ones(from left to right)
++               return b.overscaledZ - a.overscaledZ || rotatedB.y - rotatedA.y || rotatedA.x - rotatedB.x;
            }).map(tile => tile.tileID.key);
```
This will lead to several render tests be updated in gl-js.

cc: @ansis @mourner @asheemmamoowala

2026-04-21 05:50 UTC, closed without merging