docs: add links for the projections
mapbox/mapbox-gl-js pull request #11262
Opened 2021-11-09 12:40 UTC by stepankuzmin

This PR adds a note about map projection param according to https://github.com/mapbox/mapbox-gl-js-docs/pull/724#issuecomment-962288409

2021-11-09 17:14 UTC, domlet requested changes
Love it! 

I've requested a few changes on this PR, and [this change](https://github.com/mapbox/mapbox-gl-js-docs/pull/724/files#r745837006) in the example PR. 👍🏼

2021-11-09 17:14 UTC, domlet commented on src/ui/map.js
> +     * @see [Example: Use different map projections for web maps](https://docs.mapbox.com/mapbox-gl-js/example/projections/)
```suggestion
     * @see [Example: Display a web map using an alternate projection](https://docs.mapbox.com/mapbox-gl-js/example/map-projection/)
     * @see [Example: Use different map projections for web maps](https://docs.mapbox.com/mapbox-gl-js/example/projections/)
```
Adds a link to the complementary example in https://github.com/mapbox/mapbox-gl-js-docs/pull/730

2021-11-09 17:14 UTC, domlet commented on src/ui/map.js
> + * @param {ProjectionSpecification} [options.projection='mercator'] The projection the map should be rendered in.
```suggestion
 * @param {ProjectionSpecification} [options.projection='mercator'] The [projection](https://docs.mapbox.com/help/glossary/projection/) the map should be rendered in.
```
Adds a link to glossary entry.

2021-11-11 17:20 UTC, mourner approved these changes

2021-11-11 22:18 UTC, domlet approved these changes
✨

2021-11-15 17:01 UTC, merged