Fixes e.isSourceLoaded to check if specific source is loaded
mapbox/mapbox-gl-js pull request #11393
Opened 2022-01-12 21:31 UTC by avpeery

## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

2022-01-14 06:52 UTC, asheemmamoowala requested changes
The fix looks good, but is missing unit tests. There are similar tests in `geojson_source.test.js` that could be amended to test all the events from a `setData` call.

I tested against debug/geojson_update.html and found the following sequence of `sourcedata` events for a GeoJSON source:

1. `sourceDataType: metadata`: On first being added to the map and after the worker has loaded inline data or fetched and loaded from remote data. 
2. sourceDataType: content`: on calls to `setData` and after the worker has loaded inline data or fetched and loaded from remote data. 
3. `sourceDataType: undefined` for each tile required to complete rendering the current frame.

`e.isSourceLoaded` is false for every one of these emitted events until the last tile request is completed.

2022-01-18 17:20 UTC, asheemmamoowala approved these changes
Approved pending an additional unit test with `GeoJsonSource#setData` showing that `isSourceLoaded` changes to true.

2022-01-20 23:37 UTC, avpeery commented
@asheemmamoowala Thanks for the review! I added in a call to`setData` in the previous test case. If the source is not added to the map before calling `setData`, isSourceLoaded is not included in the 'data' event response (which is being set here: https://github.com/mapbox/mapbox-gl-js/blob/avpeery/fix-e.isSourceLoaded/src/source/geojson_source.js#L323). While isSourceLoaded is set here: https://github.com/mapbox/mapbox-gl-js/blob/avpeery/fix-e.isSourceLoaded/src/style/style.js#L708. Let me know if this makes sense and if these needs further conversation.

2022-01-24 19:38 UTC, asheemmamoowala approved these changes

2022-01-25 00:12 UTC, merged