Tile URL: placeholders can be duplicated
mapbox/mapbox-gl-js pull request #11441
Opened 2022-01-26 05:14 UTC by ozero

This PR fixes the problem of tile URL handling:

Current behavior: (assume z=15, x=9876, y=4321)
- Tile URL: `https://maptile.example.com/asset/{z}/{x}/{z}_{x}_{y}.gif`
- Request: `https://maptile.example.com/asset/15/9876/{z}_{x}_4321.gif`

Desirable behavior: (assume z=15, x=9876, y=4321)
- Tile URL: `https://maptile.example.com/asset/{z}/{x}/{z}_{x}_{y}.gif`
- Request: `https://maptile.example.com/asset/15/9876/15_9876_4321.gif`

## Launch Checklist

 - [ ] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [ ] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

2022-01-26 05:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=11441) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=11441) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-gl-js?pullRequest=11441) it.</sub>

2022-03-09 03:34 UTC, SnailBones requested changes
Thanks for your contribution @ozero!

Would you be willing to write a unit test to ensure that we can avoid a regression of this behavior?

2022-04-01 01:33 UTC, ozero commented
@SnailBones Ok, I update the test.
https://github.com/mapbox/mapbox-gl-js/pull/11441/commits/11c32dc0a15befab5731670ecf7e4ee5b609be36

2022-04-01 15:56 UTC, SnailBones commented on test/unit/source/tile_id.test.js
> +            t.equal(new CanonicalTileID(15, 9876, 4321).url(['{z}/{x}/{z}_{x}_{y}.json']), '15/9876/15_9876_4321.json');
Nit: Can we keep both of these?
```suggestion
            t.equal(new CanonicalTileID(1, 0, 0).url(['{z}/{x}/{y}.json']), '1/0/0.json');
            t.equal(new CanonicalTileID(15, 9876, 4321).url(['{z}/{x}/{z}_{x}_{y}.json']), '15/9876/15_9876_4321.json');
```

2022-04-04 18:18 UTC, SnailBones approved these changes
Thanks for the fix @ozero!

2022-04-04 18:26 UTC, merged