Fix map.fitBounds() with non-zero bearing
mapbox/mapbox-gl-js pull request #11568
Opened 2022-03-06 05:04 UTC by TannerPerrien

Fix bounds/bearing calculation bug (#10064) in the following methods:

* `map.fitBounds()`
* `map.fitScreenCoordinates()`
* `map.cameraForBounds()`

Consider bearings of 45 and 135 and how all four corners need to be taken into account.

Changes in tests:

* Fix tests for camera => #cameraForBounds (they were incorrect)
* Add new test for camera => #fitBounds with non-zero bearing
* Changed input coordinates in tests camera => #fitScreenCoordinates to make the input region not square

Before
<img width="1172" alt="before" src="https://user-images.githubusercontent.com/1613103/156909802-3d8e7b5d-a558-4571-a486-62fb1455c92b.png">
After
<img width="1156" alt="after" src="https://user-images.githubusercontent.com/1613103/156909804-5b642c3f-980c-454a-8764-0dcd39e8cbb8.png">

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] write tests for all new functionality
 - [x] document any changes to public APIs
 - [x] manually test the debug page
 - [x] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix bounds calculation where map.fitBounds(), map.fitScreenCoordinates(), and map.cameraForBounds() behave incorrectly with non-zero bearing. (#10064)</changelog>`

2022-03-06 05:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=11568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=11568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-gl-js?pullRequest=11568) it.</sub>

2022-03-08 18:12 UTC, SnailBones requested changes
Thanks for your work on this @TannerPerrien! I tested this out and it seems to work.

I did add a few small suggestions for code styling.

2022-03-08 21:47 UTC, TannerPerrien commented on src/ui/camera.js
> +        const p3world = tr.project(new LngLat(p1LatLng.lng, p0LatLng.lat));
Much better. Thanks!

2022-03-08 21:47 UTC, TannerPerrien commented on src/ui/camera.js
> +        const p3rotated = p3world.rotate(-bearing * Math.PI / 180);
Done!

2022-03-08 23:47 UTC, TannerPerrien commented on src/ui/camera.js
> +        const p3rotated = p3world.rotate(-degToRad(bearing));
Good call. Apologies for the slop!

2022-03-09 00:17 UTC, merged