Support referrerPolicy option for transformRequest function when using fetch
mapbox/mapbox-gl-js pull request #12590
Opened 2023-02-24 23:39 UTC by robertcepa

Hi folks, 

we recently had to change the referrer policy on our website to `same-origin` for security reasons. As a result, we are not able to use Mapbox anymore -- the change of policy caused some Mapbox APIs return 403 Forbidden, as the API requires Referer header to be set on requests in order to identify clients, which isn't allowed by our new policy. (see more at https://docs.mapbox.com/accounts/guides/tokens/#requirements-and-limitations)

We cannot relax the referrer policy globally (e.g. to `strict-origin-when-cross-origin`), but we can relax it for the specific requests to Mapbox. The solution is to use [referrerPolicy option on fetch](https://javascript.info/fetch-api).

This PR adds support for overriding referrer policy by returning it from [transformRequest](https://docs.mapbox.com/mapbox-gl-js/api/map/) callback function on Map.

Note that this feature only works in browsers that support [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) and [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) interface.

Related issues:
https://github.com/mapbox/mapbox-gl-js/issues/10309
https://github.com/mapbox/mapbox-gl-js/issues/12568

I'd be happy to add some tests but it seems that the underlying testing environment (sinon) doesn't support fetch/Request and the tests use XMLHttpRequest, which doesn't support referrer policy overrides. I tested this manually in the sandbox and also on our website by modifying `mapbox-gl-js` source code in installed node_modules and it works as intended.

2023-02-24 23:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=12590) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=12590) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-gl-js?pullRequest=12590) it.</sub>

2023-02-25 21:25 UTC, mourner approved these changes
This makes sense to me and looks like a good addition. We probably can tolerate not having tests for this as this is basically a pass-through to the Fetch API.

2023-02-25 21:31 UTC, mourner requested changes
Before we merge, can you also add a doc string above so that it will be reflected in the docs? And add a `<changelog>...<changelog>` line to the PR description so that it gets picked up by our changelog drafting tool.

2023-02-25 21:55 UTC, robertcepa commented
Thanks for the feedback, updated!

2023-02-25 21:59 UTC, mourner approved these changes

2023-02-28 13:47 UTC, merged