Update map to use fullscreenchange event when available
mapbox/mapbox-gl-js pull request #12719
Opened 2023-05-18 14:02 UTC by adamtpowell

Closes #12718.

Previously, when the browser itself was already full screen and the element containing the map had a fixed size, the map would not properly resize to become full screen if the user clicks an attached Fullscreen Control.

This issue was caused by the map registering listeners for `webkitfullscreenchange` and not for un-prefixed `fullscreenchange`. This meant that a `fullscreenchange` event wouldn't cause the map to resize.

The map expanded as expected in most cases because the size of the browser window typically changes when entering fullscreen. The map did correctly register `resize` events to cause a map resize. If the browser was already fullscreen the browser window wouldn't need to change size, so the `resize` event wouldn't fire.

This means that the bug doesn't reproduce in most `iframes`, since the `iframe` doesn't fill the entire screen even if the browser itself is in full screen.

To fix this, I added a check when registering listeners in `map.js` to use the unprefixed `fullscreenchange` if it is available.

## Changes made:
* When adding event listeners, `map.js` now checks if unprefixed `fullscreenchange` is supported and uses that instead of the previous `webkitfullscreenchange`.

## Before
![image](https://github.com/mapbox/mapbox-gl-js/assets/43593885/5edc38b6-fcfc-440c-8037-e85d01ad1445)
![image](https://github.com/mapbox/mapbox-gl-js/assets/43593885/c55fd8f1-abcb-4872-86f6-65cb7b8c899b)

## After
![image](https://github.com/mapbox/mapbox-gl-js/assets/43593885/0fa4646a-4fb3-4834-bc89-7db7a22b7a3f)
![image](https://github.com/mapbox/mapbox-gl-js/assets/43593885/67b4230e-2dd0-42d6-b955-170534e8ef09)

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [x] include before/after visuals or gifs if this PR includes visual changes
 - [x] manually test the debug page
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [x] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog>Fix map not resizing when using a Fullscreen Control while the browser is already in fullscreen.</changelog>`

2023-05-18 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=12719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mapbox/mapbox-gl-js?pullRequest=12719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mapbox/mapbox-gl-js?pullRequest=12719) it.</sub>

2023-05-18 15:03 UTC, mourner requested changes
Thanks for the contribution! There also needs to be a corresponding change in `map.remove()` so that the listener is removed.

2023-05-22 13:34 UTC, mourner approved these changes

2023-05-22 13:35 UTC, merged

2023-06-20 02:16 UTC, suryakumara commented
Hi I had the same issue, still can't make it right.

2023-06-20 04:01 UTC, adamtpowell commented
@suryakumara I don't think this change hasn't been put into a release yet

If I recall correctly, the workaround is to add a `onfullscreenchange` event listener to the window:
```
window.addEventListener('fullscreenchange', () => {
    map.resize();
});
```

2023-06-20 05:09 UTC, suryakumara commented
@adamtpowell I see, thanks for the help. I will use your method as a temporary solution. Works now.