enforce no wrapIndent for jsdoc comments
mapbox/mapbox-gl-js pull request #13139
Opened 2024-04-05 19:41 UTC by chriswhong

This PR addresses an issue that caused incorrect rendering of generated documentation on docs.mapbox.com.  

The JSDoc comments for some parameters span multiple lines, and indentation of lines is enforced by the `jsdoc/check-line-alignment` eslint rule. This repo has additional configuration to force an indentation of 4 spaces on wrapped lines.

This indentation of subsequent lines results in markdown parsing issues.  For example, the markdown to be parsed for Map.options.style looks like:

```
The map's Mapbox style. This must be an a JSON object conforming to
    the schema described in the [Mapbox Style Specification](https://mapbox.com/mapbox-gl-style-spec/), or a URL
    to such JSON. Can accept a null value to allow adding a style manually.
    
    To load a style from the Mapbox API, you can use a URL of the form `mapbox://styles/:owner/:style`,
    where `:owner` is your Mapbox account name and `:style` is the style ID. You can also use a
    [Mapbox-owned style](https://docs.mapbox.com/api/maps/styles/#mapbox-styles):
    * `mapbox://styles/mapbox/standard`
    * `mapbox://styles/mapbox/streets-v12`
    * `mapbox://styles/mapbox/outdoors-v12`
    * `mapbox://styles/mapbox/light-v11`
    * `mapbox://styles/mapbox/dark-v11`
    * `mapbox://styles/mapbox/satellite-v9`
    * `mapbox://styles/mapbox/satellite-streets-v12`
    * `mapbox://styles/mapbox/navigation-day-v1`
    * `mapbox://styles/mapbox/navigation-night-v1`.
```
The first three lines are parsed as a paragraph, but the lines after the empty line are parsed as a codeblock, and renders as such on docs.mapbox.com:

<img width="662" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/1833820/fc6083e7-6246-4721-ab27-f1ea6d67825e">

This PR removes the `wrapIndent` option, enforcing no indentation on wrapped lines.  The resulting JSDoc comments were tested locally with `mapbox-gl-js-docs` and result in correct rendering in the docs:

<img width="681" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/1833820/c7a6061d-311c-4311-b4c3-e99298bda5a4">

I am not clear on the repercussions of this change to other things that make use of the JSDoc comments, if any, and seek guidance from others with more experience with this codebase on whether this change is safe. 

## Launch Checklist

 - [ ] Make sure the PR title is descriptive and preferably reflects the change from the user's perspective.
 - [ ] Add additional detail and context in the PR description (with screenshots/videos if there are visual changes).
 - [ ] Manually test the debug page.
 - [ ] Write tests for all new functionality and make sure the CI checks pass.
 - [ ] Document any changes to public APIs.
 - [ ] Post benchmark scores if the change could affect performance.
 - [ ] Tag `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes.
 - [ ] Tag `@mapbox/gl-native` if this PR includes shader changes or needs a native port.

2024-04-06 08:22 UTC, stepankuzmin approved these changes

2024-04-09 13:57 UTC, chriswhong commented on .eslintrc
> +        "jsdoc/check-line-alignment": ["error"],
According to the README, the default for `wrapIndent` is the empty string. https://github.com/gajus/eslint-plugin-jsdoc/blob/HEAD/docs/rules/check-line-alignment.md#wrapindent

2024-04-10 09:42 UTC, mourner requested changes
Looks good to me apart from 2 lint failures — let's get the build green before merging.

2024-05-03 16:08 UTC, chriswhong commented
@mourner checks are passing, can you merge when ready?

2024-05-15 08:29 UTC, mourner approved these changes

2024-05-15 08:29 UTC, merged