change hash without affecting the rest of URL
mapbox/mapbox-gl-js pull request #9960
Opened 2020-08-28 15:03 UTC by raegen

Closes #9955 . Hash change currently replaces history state url with only the updated hash, ignoring the current URL (path, query parameters etc). This PR fixes the hash change method, so that it updates only the fragment (part in case of a named fragment parameter), while leaving the rest of URL untouched.

## Launch Checklist

 - [x] briefly describe the changes in this PR
 - [ ] include before/after visuals or gifs if this PR includes visual changes
 - [ ] write tests for all new functionality
 - [ ] document any changes to public APIs
 - [ ] post benchmark scores
 - [x] manually test the debug page
 - [ ] tagged `@mapbox/map-design-team` `@mapbox/static-apis` if this PR includes style spec API or visual changes
 - [ ] tagged `@mapbox/gl-native` if this PR includes shader changes or needs a native port
 - [ ] apply changelog label ('bug', 'feature', 'docs', etc) or use the label 'skip changelog'
 - [ ] add an entry inside this element for inclusion in the `mapbox-gl-js` changelog: `<changelog></changelog>`

2020-08-31 08:51 UTC, mourner approved these changes

2020-08-31 09:21 UTC, mourner requested changes
Not sure why CI didn't run on the initial commit, but after bumping it, I see a ton of unit test failures — can you look at fixing those?

2020-09-01 11:18 UTC, raegen commented
On it

2020-09-01 11:34 UTC, raegen commented
@mourner there you go :)

2020-09-01 11:36 UTC, mourner approved these changes
🙏

2020-09-01 11:36 UTC, merged